Saule/ApiResource.cs
Saule/ResourceRelationship.cs
Tests/ApiResourceTests.cs
Website/Resources/TestResource.cs

Handle cyclic relationships correctly

---

Saule/Serialization/ResourceSerializer.cs
Tests/Helpers/Person.cs
Tests/Serialization/DefaultUrlPathBuilderTests.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Serialization/UrlConstructionTests.cs

- corrected spelling of 'corporation'
- output serialized test results for easier visual inspection

unit test improvements

---

Saule/Serialization/DefaultUrlPathBuilder.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/UrlConstructionTests.cs

Change self paths to conform to the spec

---

appveyor.yml
set-version.ps1

new release scheme to allow cutting more controlled releases

Only push when there's a tag

---

.gitignore
Saule/Queries/SortingInterpreter.cs
Saule/Serialization/DefaultUrlPathBuilder.cs
Tests/Controllers/PeopleController.cs
Tests/Http/AttributeTests.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/JsonApiSerializerTests.cs
Tests/Queries/PaginationInterpreterTests.cs
Tests/Queries/SortingInterpreterTests.cs
Tests/Serialization/CanonicalUrlPathBuilderTests.cs
Tests/Serialization/DefaultUrlPathBuilderTests.cs
Tests/Tests.csproj
Website/App_Start/WebApiConfig.cs

Increase test coverage

---

Saule/Serialization/ApiError.cs
Tests/Controllers/BrokenController.cs
Tests/Helpers/JsonApiServer.cs
Tests/Integration/ContentNegotiationTests.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/JsonApiSerializerTests.cs
Tests/Queries/SortingInterpreterTests.cs
Tests/Serialization/ErrorSerializerTests.cs
Tests/Tests.csproj
Tests/app.config
Tests/packages.config

Test server instead of http server

---

Saule/packages.config

change dependencies

---

Tests/Helpers/Get.cs
Tests/Serialization/ResourceSerializerTests.cs

Just to make sure we don't implicitly rely on fixed values anywhere.

Introduce random names to tests

---

CHANGELOG.md
Saule/Constants.cs
Saule/Http/AllowsQueryAttribute.cs
Saule/JsonApiException.cs
Saule/JsonApiSerializer.cs
Saule/JsonApiSerializerOfT.cs
Saule/Queries/Filtering/FilteringContext.cs
Saule/Queries/Filtering/FilteringInterpreter.cs
Saule/Queries/Filtering/FilteringProperty.cs
Saule/Queries/Lambda.cs
Saule/Queries/Query.cs
Saule/Queries/QueryContext.cs
Saule/Queries/QueryMethod.cs
Saule/Queries/Sorting/SortingInterpreter.cs
Saule/Saule.csproj
Tests/Controllers/CompaniesController.cs
Tests/Controllers/PeopleController.cs
Tests/Helpers/Get.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/JsonApiSerializerTests.cs
Tests/Queries/FilteringInterpreterTests.cs
Tests/Queries/SortingInterpreterTests.cs
Tests/Tests.csproj

Add filtering support

---

Saule/ApiResource.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Models/CompanyWithDifferentId.cs
Tests/Models/CompanyWithDifferentIdResource.cs
Tests/Models/PersonWithDifferentId.cs
Tests/Models/PersonWithDifferentIdResource.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj

Add support for custom id properties

---

CHANGELOG.md
Saule/Http/HttpConfigExtensions.cs
Saule/Http/JsonApiConfiguration.cs
Saule/Http/JsonApiMediaTypeFormatter.cs
Saule/Saule.csproj
Tests/Helpers/NewSetupJsonApiServer.cs
Tests/Helpers/ObsoleteSetupJsonApiServer.cs
Tests/Integration/ContentNegotiationTests.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/Tests.csproj

Introduce new way to set up Saule

---

Saule/JsonApiSerializer.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Models/Recursion.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj

Allow models to have recursive references

---

Saule/ApiResource.cs
Saule/Constants.cs
Saule/Http/HttpConfigExtensions.cs
Saule/Http/JsonApiConfiguration.cs
Saule/Http/JsonApiMediaTypeFormatter.cs
Saule/Http/PreprocessingDelegatingHandler.cs
Saule/JsonApiException.cs
Saule/JsonApiSerializer.cs
Saule/JsonApiSerializerOfT.cs
Saule/PreprocessResult.cs
Saule/Queries/Filtering/FilteringInterpreter.cs
Saule/Queries/Pagination/PaginationInterpreter.cs
Saule/Queries/Sorting/SortingInterpreter.cs
Saule/Saule.csproj
Saule/Serialization/ApiError.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Helpers/HttpClientExtensions.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/Serialization/ErrorSerializerTests.cs

Return correct status code for JsonApiExceptions

---

CHANGELOG.md
Saule/JsonApiSerializer.cs
Saule/Queries/Filtering/FilteringInterpreter.cs
Saule/Queries/Pagination/PaginationInterpreter.cs
Saule/Queries/Query.cs
Saule/Queries/Sorting/SortingInterpreter.cs
Tests/Controllers/PeopleController.cs
Tests/Models/CompanyResource.cs
Tests/Models/Person.cs
Tests/Models/PersonResource.cs
Tests/Models/PersonWithDefaultIdResource.cs
Tests/Models/PersonWithDifferentIdResource.cs
Tests/Queries/FilteringInterpreterTests.cs
Tests/Queries/PaginationInterpreterTests.cs
Tests/Queries/SortingInterpreterTests.cs
Tests/Serialization/ResourceDeserializerTests.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj
Website/App_Start/WebApiConfig.cs

support custom ids everywhere

---

Saule/JsonApiSerializer.cs
Saule/Queries/Lambda.cs
Tests/Models/Person.cs
Tests/Serialization/ResourceDeserializerTests.cs

Allow filtering on nullable types

---

Saule/JsonApiSerializer.cs

Don't try to apply filtering, sorting or pagination to an error response.

fix error serialization

---

Saule/Serialization/DefaultUrlPathBuilder.cs
Tests/Controllers/CompaniesController.cs
Tests/Controllers/PeopleController.cs
Tests/Serialization/DefaultUrlPathBuilderTests.cs

Improve url root path discovery

---

Saule/Constants.cs
Saule/Http/PreprocessingDelegatingHandler.cs
Saule/Serialization/DefaultUrlPathBuilder.cs
Tests/Serialization/DefaultUrlPathBuilderTests.cs

Always prefix IIS virtual path root

---

Saule/Http/PreprocessingDelegatingHandler.cs
Tests/Controllers/BrokenController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs

Don't hide HttpError

---

CHANGELOG.md
Saule/Http/PreprocessingDelegatingHandler.cs
Tests/Controllers/BrokenController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
appveyor.yml

Fixes #84 for the `1.4` release.

Fix regression: `HttpError` not passed through

---

Saule/Constants.cs
Saule/Http/AllowsQueryAttribute.cs
Saule/Http/HttpConfigExtensions.cs
Saule/Http/JsonApiMediaTypeFormatter.cs
Saule/Http/PaginatedAttribute.cs
Saule/Http/PreprocessingDelegatingHandler.cs
Saule/Http/ReturnsResourceAttribute.cs
Saule/Queries/Filtering/FilteringContext.cs
Saule/Queries/Pagination/PaginationContext.cs
Saule/Queries/Pagination/PaginationQuery.cs
Saule/Queries/Sorting/SortingContext.cs
Tests/Queries/FilteringInterpreterTests.cs
Tests/Queries/PaginationInterpreterTests.cs
Tests/Queries/PaginationQueryTests.cs
Tests/Queries/SortingInterpreterTests.cs
Tests/Serialization/UrlConstructionTests.cs

More flexible setup

---

Saule/Serialization/ResourceDeserializer.cs
Tests/Serialization/ResourceDeserializerTests.cs

Support belongsTo relationships when data is null

---

Saule/Http/ReturnsResourceAttribute.cs
Tests/Integration/ContentNegotiationTests.cs

My take on https://github.com/joukevandermaas/saule/issues/100 and https://github.com/joukevandermaas/saule/issues/146.

Do not require Accept header

---

Saule.sln
Saule/ApiResource.cs
Saule/LinkType.cs
Saule/Saule.csproj
Saule/Serialization/ResourceSerializer.cs
Tests/Models/PersonResource.cs
Tests/Serialization/MetadataTests.cs
Tests/Tests.csproj
docs/Generating-links.md
docs/Pagination.md
docs/Queryable-endpoints.md
docs/Resource-models.md
docs/metadata.md

Add support for metadata

---

Saule/Serialization/ResourceSerializer.cs
Saule/TypeExtensions.cs

Also avoids reflection on type name.

Refactor collection type extractor into TypeExtensions

---

Saule/Serialization/ResourceSerializer.cs
Tests/Models/PersonResource.cs
Tests/Serialization/ResourceSerializerTests.cs

Related to https://github.com/joukevandermaas/saule/issues/159.

Omit data for relationship objects not existing as property in the original model

---

Saule/ApiResource.cs
Saule/Http/FilterExpressions/LambdaQueryFilterExpression.cs
Saule/Queries/Filtering/FilteringContext.cs
Saule/Queries/Filtering/FilteringProperty.cs
Saule/Queries/Including/IncludingContext.cs
Saule/Queries/Including/IncludingProperty.cs
Saule/Queries/Pagination/PaginationContext.cs
Saule/Queries/QueryContext.cs
Saule/Queries/Sorting/SortingContext.cs
Saule/Queries/Sorting/SortingProperty.cs
Saule/ResourceAttribute.cs
Saule/ResourceRelationship.cs
Saule/Serialization/ResourceGraphNode.cs
Saule/Serialization/ResourceGraphRelationship.cs

By adding `ToString` implementations by some types you'll inspect often.

Ease debugging a bit

---

Tests/Tests.csproj
Tests/packages.config

Fix issue running tests similar to https://github.com/Microsoft/vstest/issues/1220.

Upgrade xunit dependencies

---

Saule/Saule.csproj
Saule/app.config
Saule/packages.config
Tests/Properties/Resources.Designer.cs
Tests/Tests.csproj
Tests/app.config
Tests/packages.config

This replaces https://github.com/joukevandermaas/saule/pull/216 and https://github.com/joukevandermaas/saule/pull/217.

Upgrade dependencies and target .NET 4.7
