Saule/Http/PaginatedAttribute.cs
Saule/JsonApiSerializer.cs
Saule/Queries/PaginationInterpreter.cs
Saule/Queries/QueryMethod.cs
Saule/Saule.csproj
Saule/Serialization/ResourceSerializer.cs
Tests/JsonApiSerializerTests.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj
appveyor.yml

* Move pagination logic out of the attribute
* Add class to handle serialization
* Add tests
Hopefully we can start using `JsonApiSerializer` from within `JsonApiMediaTypeFormatter` soon, but for now it's problematic due to generics.
Closes #17.

public serializer

---

Saule/Http/JsonApiMediaTypeFormatter.cs
Tests/Http/JsonApiMediaTypeFormatterTests.cs
Tests/Tests.csproj

Serious bug. Media type not registered, so NO json api support at all when used in web site.

bug fix - missing Json Api media type

---

Saule/Serialization/ApiError.cs
Tests/Serialization/ErrorSerializerTests.cs

Meaningful errors were being suppressed when, for example, I accidentally added a duplicate Attribute in my Resource definition.

add recursive exception message to ApiError

---

CHANGELOG.md
Saule/Http/FilterExpressions/CaseInsensitiveStringQueryFilterExpression.cs
Saule/Http/FilterExpressions/DefaultQueryFilterExpression.cs
Saule/Http/FilterExpressions/LambdaQueryFilterExpression.cs
Saule/Http/IQueryFilterExpression.cs
Saule/Http/JsonApiConfiguration.cs
Saule/Http/JsonApiMediaTypeFormatter.cs
Saule/Http/QueryFilterExpressionCollection.cs
Saule/JsonApiSerializer.cs
Saule/JsonApiSerializerOfT.cs
Saule/Properties/AssemblyInfo.cs
Saule/Queries/EnumerableExtensions.cs
Saule/Queries/Filtering/FilteringContext.cs
Saule/Queries/Filtering/FilteringInterpreter.cs
Saule/Queries/Filtering/TypeCorrectingVisitor.cs
Saule/Queries/Lambda.cs
Saule/Queries/Query.cs
Saule/Saule.csproj
Saule/TypeExtensions.cs
Saule/app.config
Saule/packages.config
StyleCop.Analyzers.ruleset
Tests/Helpers/ExpressionComparer.cs
Tests/Http/QueryFilterExpressionCollectionTests.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/JsonApiSerializerTests.cs
Tests/Tests.csproj

When this pr is done, a user should be able to manipulate the filter that is used internally, e.g.:
```csharp
MyFilters.Set<string>((left, right) => left.ToUpperInvariant() == right.ToUpperInvariant());
```
for case-insensitive filtering on strings, or
```csharp
MyFilters.Set<string>((left, right) => left.Contains(right));
```
for substring search. At runtime, these will be substituted for the real values, e.g.:
```csharp
returnedQueryable.Where((i) => i.SomeProperty.Contains(someFilter));
```
Note that all filters derive from `IQueryFilterExpression<T>`, which also has access to the `PropertyInfo` of the property that is being filtered on. This way, you could theoretically implement different filtering for specific properties, while doing some default for others. Saule will likely leave …

allow generic overriding of filtering lambdas

---

CHANGELOG.md
Saule/Http/JsonApiConfiguration.cs
Saule/Http/PreprocessingDelegatingHandler.cs
Saule/Serialization/DefaultUrlPathBuilder.cs
Tests/Controllers/BrokenController.cs
Tests/Controllers/CompaniesController.cs
Tests/Controllers/PeopleController.cs
Tests/Helpers/Paths.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs

This makes the 'prefix' parameter unnecessary for `DefaultUrlPathBuilder` in 90% of cases. Fixes #71.
This works by assuming that urls take the form `/prefix/resource/{id}/` where `{id}` is optional. If that is not true for you, you should still use 'prefix' or implement `IUrlPathBuilder`.

Find url namespace by default

---

Saule/Http/PreprocessingDelegatingHandler.cs
Tests/Controllers/CompaniesController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs

This allows you to create e.g. a delete without having to specify an unused `ReturnsResourceAttribute`.

don't require attribute for empty responses

---

Saule/Serialization/ResourceSerializer.cs
Tests/Models/GuidAsRelation.cs
Tests/Models/PersonWithGuidAsRelationsResource.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj

The use of Guids as id's leads to the following types of exception when id's are converted to strings:
```
{System.InvalidCastException: Object must implement IConvertible.
at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
at Saule.Serialization.ResourceSerializer.<>c__DisplayClass23_0.<GetRelationshipData>b__0(IDictionary`2 props)
at Saule.Serialization.ResourceSerializer.SerializeArrayOrObject(JToken token, Func`2 serializeObj)
at Saule.Serialization.ResourceSerializer.GetRelationshipData(ResourceRelationship relationship, JToken relationshipValues)
at …
```

use Guids as id's

---

Saule/Serialization/ResourceSerializer.cs
Tests/Models/Recursion.cs
Tests/Serialization/ResourceSerializerTests.cs

Added functionality that recursively serializes a model, placing all nested objects in the `included` array. This conforms to the JSON API spec, which states:
http://jsonapi.org/format/#document-top-level
A document MAY contain any of these top-level members:
- jsonapi: an object describing the server’s implementation
- links: a links object related to the primary data.
- **included: an array of resource objects that are related to the primary data and/or each other (“included resources”).**

Serialize recursively placing all nested objects in the 'included' array

---

Saule/Http/PreprocessingDelegatingHandler.cs
Tests/Controllers/StaticController.cs
Tests/Helpers/Paths.cs
Tests/Integration/ContentNegotiationTests.cs
Tests/Tests.csproj

This modification checks for the presence of the JSONAPI media type within the accept header before executing the body of the PreprocessingDelegatingHandler. This prevents the handler from breaking non-API routes for static or other content. An associated test has been added against a controller serving static content. Should resolve #111 and #116.

Fix for #111 and #116

---

Saule/Serialization/ResourceSerializer.cs
Tests/Helpers/Get.cs
Tests/Models/CompanyWithCustomers.cs
Tests/Models/CompanyWithCustomersResource.cs
Tests/Models/Customer.cs
Tests/Models/CustomerResource.cs
Tests/Models/PersonWithCompanyWithCustomersResource.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj

Whilst working on an Ember Data app, I noticed that Saule was using the root resource's URL path when generating links for included resources, rather than using the URL path of the included resource. This PR fixes this in my case.

Use included resource when serialising it’s links

---

Saule/ApiResource.cs
Saule/ResourceAttribute.cs

Needed for external inspection to for example generate schema.
Can solve part of #140.

Expose properties of resource

---

Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/ResourceSerializerTests.cs

This addresses a problem I came across when Saule is serialising an array of resources. If any of the resources in the array have relationships with each other, then it will also add the related resources to the included section. 
The JSON:API spec asks that resources in compound documents should be unique across the data and included sections. http://jsonapi.org/format/#document-compound-documents
This PR trims resources from the included section where they are present in the data section once resource serialisation is complete.

Prevent a resource being included in both the data and included sections

---

Saule/ApiResource.cs
Saule/ResourceRelationship.cs
Saule/ResourceRelationshipOfT.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Models/PersonJobOnlyRelatedLinksResource.cs
Tests/Models/PersonJobOnlySelfLinksResource.cs
Tests/Models/PersonNoJobLinksResource.cs
Tests/Models/PersonNoLinksResource.cs
Tests/Serialization/CanonicalUrlPathBuilderTests.cs
Tests/Serialization/DefaultUrlPathBuilderTests.cs
Tests/Serialization/UrlConstructionTests.cs
Tests/Tests.csproj
docs/Generating-links.md

Aims to resolve #150.
Not yet finished though but wanted to ask about the approach. I couldn't see it possible to handle this in the `UrlPathBuilder` but had to involve the `ResourceSerializer`. Also, I'm not sure about what a "canonical" url is and so have problems understanding the purpose of Related vs RelatedCanonical.

Optional links support

---

Saule/Serialization/ResourceGraph.cs
Saule/Serialization/ResourceGraphNode.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/ResourceSerializerTests.cs

Initially this PR added a test that fails on master but passes in stable to demonstrate the issue. The issue only reveals itself when DisableDefaultIncluded is used.
Now a fix is also included in this PR. It includes relationship data in the graph when using `DisableDefaultIncluded`, adds information of the parent property name for nodes which are children. It then uses this information when serializing the `includes` value.
Ping @laurence79.

Fix regression missing 'data' key for relationships when using DisableDefaultIncluded

---

Saule/ConfigureFormattersEnum.cs
Saule/FormatterPriority.cs
Saule/Http/HttpConfigExtensions.cs
Saule/Saule.csproj

I added more options for configure formatters in ConfigureJsonApi. For example if want combinate JSON API with WebAPI together.
#167

configureJsonApi overload (formatter can be only add at end of the collection, without delete other formatters

---

Saule/Constants.cs
Saule/Http/JsonApiConfiguration.cs
Saule/Http/PaginatedAttribute.cs
Saule/Http/PaginationConfig.cs
Saule/Http/PreprocessingDelegatingHandler.cs
Saule/Queries/Pagination/PaginationContext.cs
Saule/Saule.csproj
Saule/StringDictionaryExtensions.cs
Tests/Controllers/CompaniesController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/Serialization/UrlConstructionTests.cs
Tests/Tests.csproj
docs/Pagination.md

This pull request is for issue #128 (https://github.com/joukevandermaas/saule/issues/128#issuecomment-312198306).  Default values for page size and page size limits can be configured imperatively at app start with the JsonApiConfiguration.PaginationConfig property, or with web.config appSetting values.  See the PaginationConfig PageSizeAppSettingKey and PageSizeLimitKey constants.  The Pagination attribute has had a PageSizeLimit property added for overriding the application default values.
I hold the opinion that with page[size] from the query implemented, that the default of 10 as it existed with the Pagination attribute should be done away with, and that the library should require both page[number] and page[size] if either is supplied, but this implementation has the page size default …

Added pagination page size

---

Saule/JsonApiSerializerOfT.cs
Saule/Serialization/ResourceDeserializer.cs
Tests/JsonApiSerializerTests.cs

When testing APIs, it's super useful to be able to use `ResourceDeserializer` to deserialize json into specific objects.
We might for example receive a json string containing user data and nested data about the organization the user belongs to.
The json string can then be converted to a user object containing an organization object like this:
```
public T ConvertJson(string json) where T : class
{
var jObject = JObject.Parse(json);
var target = new ResourceDeserializer(jObject, typeof(T));
return target.Deserialize() as T;
}
```

Made ResourceDeserializer public

---

Saule/ApiResource.cs
Saule/ResourceRelationship.cs
Saule/ResourceRelationshipOfT.cs
Saule/Serialization/ResourceSerializer.cs
Tests/JsonApiSerializerTests.cs
Tests/Serialization/ResourceSerializerTests.cs

Hey man,
love this library it is awesome. 
Just wanted to submit a potential change. To not serialize the "data" on a relationship when that relationship was null. Just referring to this part of the standard (http://jsonapi.org/format/#document-resource-object-relationships) "A “relationship object” MUST contain at least one of the following:".
Cheers
Trent

Do not serialize "data" on a relationship when the relationship value is null

---

Saule/Serialization/ResourceSerializer.cs
Tests/JsonApiSerializerTests.cs
Tests/Serialization/ResourceSerializerTests.cs

Regression was caused by https://github.com/joukevandermaas/saule/pull/180. When a one-to-one relationship is empty data would be omitted and that is invalid for a relationship object without links - and it would be unfortunate to be forced to include links for nullable one-to-one relationships.

Fix regression with omitted data

---

Saule/Http/JsonApiAttribute.cs
Saule/Http/JsonApiProcessor.cs
Saule/Http/PreprocessingDelegatingHandler.cs
Saule/Saule.csproj
Tests/Controllers/CompaniesController.cs
Tests/Helpers/ObsoleteSetupJsonApiServer.cs
Tests/Integration/ContentNegotiationTests.cs

For existing WebApi projects, that don't use JsonApi/Saule we need a way to preserve backwards compatibility and opt into JsonApi on a case by case basis.
For example: `api/v2/companies` uses the attribute filter `JsonApi` which configures it to return a JsonAPI response instead of the default response.
<kbd>![image](https://user-images.githubusercontent.com/2644202/38332360-6a424d46-381b-11e8-897c-cc5a95f2c3fd.png)</kbd>
With this change, it's not necessary to call `ConfigureJsonApi` during application startup:
<kbd>![image](https://user-images.githubusercontent.com/2644202/38332266-32ca5b56-381b-11e8-9fe9-102158803fdb.png)</kbd>

opt into JsonApi per webapi endpoint

---

Saule/Http/JsonApiAttribute.cs

If a webApi method throws an exception the `context.Response` [here](https://github.com/joukevandermaas/saule/blob/master/Saule/Http/JsonApiAttribute.cs#L20) will be null which throws a NullReferenceException masking the underlying exception.  This PR fixes this problem.

properly throw exceptions when using JsonApi attribute filter

---

Saule/Constants.cs
Saule/Http/AllowsQueryAttribute.cs
Saule/JsonApiSerializer.cs
Saule/JsonApiSerializerOfT.cs
Saule/Queries/Fieldset/FieldsetContext.cs
Saule/Queries/Fieldset/FieldsetProperty.cs
Saule/Queries/QueryContext.cs
Saule/Saule.csproj
Saule/Serialization/ResourceSerializer.cs
Tests/JsonApiSerializerTests.cs
Tests/Serialization/MetadataTests.cs
Tests/Serialization/ResourceDeserializerTests.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Serialization/UrlConstructionTests.cs

This is really a first throw of me to check if you are okay with this or if you have anything against it. I also fixed all tests and added one more test. As I am not that fluent in C# and WebAPI tho I can't really tell if this is enough.
Be sure to get back to me with any comments you have and what you need changed to make a PR possible.
~Cheers

Added fields as query parameter

---

Saule/Http/PreprocessingDelegatingHandler.cs
Tests/Controllers/BrokenController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs

Hi Jouke,
Looks like i had an issue last time when i added logic to support case when more than one HttpError is returned. If controller\action doesn't have ReturnResource then for just one HttpError it will work fine and will return that error. But for the list of httpErrors it will try to use ReturnResource. It works fine as deeper it still will use ErrorSerializer, but there is one case that doesn't work.
We have base controller that has some custom attributes, and all controllers inherit it. So base one doesn't have any ReturnResource attributes. But we have some some generic handling there and we can return more than one HttpError there and without that change it just throws an error that ReturnResource is missing
I added logic to check for both HttpError and IEnumerable<HttpError> …

Added logic to still return HttpErrors if there are more than one and if endpoint\controller doesn't have specified ReturnsResource

---

Saule/LinkType.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Models/PersonOnlyTopLinksResource.cs
Tests/Serialization/UrlConstructionTests.cs
Tests/Tests.csproj

Hi Jouke,
It's a PR for #201 item. I tried to preserve back compatibility and all existing tests are passing fine. I also added new one to test Top only scenario.
Thanks

added LinkType.Top enum, so we can specify only top level links

---

Saule/Http/AllowsQueryAttribute.cs
Saule/Http/DisableDefaultIncludedAttribute.cs
Saule/Http/PaginatedAttribute.cs

I'd like to be able to specify DisableDefaultIncludedAttribute, AllowsQueryAttribute, and PaginatedAttribute at the class (ApiController) level so that all endpoints in a controller and any derived controllers share these settings. This is especially important for DisableDefaultIncludedAttribute, because accidentally including all related resources can have unknown performance implications.

Allow attributes on class

---

Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Serialization/UrlConstructionTests.cs

Hi Jouke,
This is small PR to fix one small issue. It happens for us only when we host it under IIS (Win10\WinServer 2016 and probably all others too).
The issue is that top self link always includes port even if port is standard like this:
```
"links": {
"self": "http://localhost:80/SauleExample/api/values"
}
```
or like this
```
"links": {
"self": "https://localhost:443/SauleExample/api/values"
}
```
It's still valid url as it can contain port, but it looks a bit weird. Somehow IIS always pushes port in the `Request.Url` and `_baseUrl.OriginalUrl` always has it, and when we pass Uri as object for serialization, then Newtonsoft.Json uses `.OriginalUrl` and it gives us 80\443 ports for regular http\https hosting.
I pushed change to use `_baseUri.AbsoluteUri` in the `ResourceSerializer` …

used _baseUrl.AbsoluteUri instead of _baseUrl to avoid included port number in the self link

---

Saule/Queries/Lambda.cs
Tests/Helpers/Get.cs
Tests/Queries/FilterInterpreterTests.cs

Also added a unit test. Any changes needed?

Added nested filter

---

Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/UrlConstructionTests.cs

Hi Jouke,
It's a follow up for already merged PR #206 . After we started to use paging, we found one issue with that old one PR. If initial query has parameters like `page[number]`, etc, then it WebApi might encode them and then `HttpRequestMessage.RequestUri` would have already encoded one, and then `links.self` would have encoded value. 
Here is what we are getting for endpoint that supports paging when we access such endpoint - https://localhost/WebService4/v5/internal/locations/marketplace?page[number]=2
```
{
"data": [
{
"type": "marketplace-location",
"id": "6927",
"links": {
"self": "https://localhost/WebService4/v5/internal/locations/locations/marketplace/6927/"
},
"attributes": {
...
}
}
],
"links": {
"self": "https://localhost/WebService4/v5/internal/locations/marketplace?page%5B …
```

Fixed issue with encoding for `links.self` item

---

Saule/Queries/Pagination/PaginationQuery.cs
Tests/Serialization/UrlConstructionTests.cs

Hi Jouke,
We found one missing case in initial pagination request. When we have FirstPage as `1`, then we shouldn't generate `links.prev` if current page is `1`. Like in example below `prev` link shouldn't be present as first page is `1`
```
"links": {
"self": "https://localhost/WebService4/v5/internal/locations/marketplace?page[number]=1",
"first": "https://localhost/WebService4/v5/internal/locations/marketplace?page[number]=1",
"next": "https://localhost/WebService4/v5/internal/locations/marketplace?page[number]=2",
"prev": "https://localhost/WebService4/v5/internal/locations/marketplace?page[number]=0",
"last": "https://localhost/WebService4/v5/internal/locations/marketplace?page[number]=12"
}
```
I added unit test to cover that scenario and sorry for initially missed case :) 
Thanks!

Fixed `links.prev` logic if first page number isn't zero

---

Saule/Queries/Pagination/PagedResultQuery.cs
Tests/Controllers/CompaniesController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs
Tests/Models/CustomPagedResult.cs
Tests/Tests.csproj

Hey Jouke,
Sorry, but it's another PR for another missing thing :) we tried to use custom PagedResult<T> class. We use it like 
```
public class XPagedResult<T>: PagedResult<T>
{
public int? TotalPages { get; set; }
}
```
And then for JSON.API it won't display TotalPages, but for regular JSON it will display that TotalPages field too plus properties in the base class. 
The problem is my initial code in `PagedResuleQuery.IsPagedResult` was checking for specific type but it should also check the base classes too. I've fixed it in this PR and added unit test to cover that scenario too
Thanks!

Fixed pagination when endpoint uses custom PagedResult<T> type

---

Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/UrlConstructionTests.cs

Reason
When doing a Post/Put for a single resource object using a custom route for example /location/{id}/rooms where a room was being created, the generated return self link would be generated as /locations/48/rooms/ rather then the expected /locations/48/rooms/{roomid}
POST <url>/locations/48/rooms/ 
```
{ 
"data" : 
{ 
"type" : "rooms", 
"attributes" : 
{ 
"name" : "___hxLnCfZU60", 
"capacity" : 100, 
"description" : "Generated by automation using the v5 endpoint" 
} 
} 
}
```
Return
```
{
"data" : {
"type" : "rooms",
"id" : "12684",
"attributes" : {
"name" : "___hxLnCfZU60",
"capacity" : 100,
"description" : "Generated by automation using the v5 endpoint"
}
},
"links" : {
"self" : "<url>/locations/48/rooms/"
}
}
```
What we did was look to see if the returned resource was a collection …

Allow for self link generation for custom routes

---

Saule/Queries/Pagination/PaginationQuery.cs
Tests/Controllers/CompaniesController.cs
Tests/Integration/JsonApiMediaTypeFormatterTests.cs

Hi Jouke,
Looks like we missed one more case initially. When endpoint doesn't return any items, then `links.last` will have incorrect result. 
If we would use `1` as first page number, then the response would be
```
{
"data" : [ ],
"links" : {
"self" : "https://some/v5/equipment/",
"first" : "https://some/v5/equipment/?page[number]=1",
"last" : "https://some/v5/equipment/?page[number]=0"
}
}
```
and `last` has `page[number]=0` that isn't correct and should be the same as `first`.
And if we don't have custom `firstPage` and by default it's `0`, then response would be
```
{
"data" : [ ],
"links" : {
"self" : "https://some/v5/equipment/",
"first" : "https://some/v5/equipment/?page[number]=1",
"last" : "https://some/v5/equipment/?page[number]=-1"
}
}
```
This PR is the fix for that logic and …

Fixed links.last when there are no any items in response

---

Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/UrlConstructionTests.cs

Found issue due to the change made here
#231
Due to using the `EndsWith` method, I missed the case where a user could be using a text based ID with different casing. While developing a new endpoint I saw that the ID was appended twice on the end of the URL.
Added Unit test to catch this in the future.
Solution
Added the `StringComparison.InvariantCultureIgnoreCase` argument to the `endswith` logic.

Fix Self Links ID casing

---

Saule/JsonApiSerializer.cs
Saule/Saule.csproj
Saule/Serialization/JsonApiContractResolver.cs
Saule/Serialization/ResourceSerializer.cs
Saule/Serialization/SourceContractResolver.cs
Tests/Helpers/DateISOConverter.cs
Tests/Models/PersonWithJsonConverters.cs
Tests/Models/PersonWithJsonConvertersResource.cs
Tests/Serialization/ResourceSerializerTests.cs
Tests/Tests.csproj

Added the ability for JsonConverters attached to the sourceobject properties to be triggered. Had to add filtering and depth counter to the ContractResolver so we don't serialize the whole object.
After some discussion about how this could be added. We didn't want to try and add logic that was creating instances of the converters that we might have to support given the number of different converters available. This simply invokes the Converters through the standard Json.Net serialization process.
This is missing tests, I will add them if you think this is a good solution, but it passes all existing ones. This aims to solve issue #237 
Looking for input or alternative ways to achieve the same result.

Add JsonConverter Functionality On Serialization

---

Saule/Serialization/ResourceSerializer.cs
Tests/Serialization/ResourceSerializerTests.cs

Hi Jouke, 
Looks like as part of #238 there was introduced a new issue. If ApiResource has relationship and a caller requested `?include=some` then it will return that object but all attributes in the included object would be `null`. It happens as that PR filters out properties that aren't in the current `ApiResource` but in case of Included that code still searches in the current `ApiResource`. 
i updated it and now it creates serializer based on `ApiResource` from the `ResourceGraphNode` so it might be different depending on the object. I also added caching in `Dictionary` as `DefaultContractResolver`  (and our inheritor `SourceContractResolver`) caches properties that it got from the Type but only as part of that instance so we can't recreate it each time.
i also used regular …

Fixed attributes serialization for included objects

---

Saule/Resources/DefaultApiResourceProvider.cs
Saule/Resources/IApiResourceProvider.cs
Saule/Serialization/ResourceGraph.cs
Saule/Serialization/ResourceSerializer.cs
Tests/Controllers/ShapeController.cs
Tests/Integration/JsonApiFormatterInheritenceTests.cs
Tests/Models/Inheritance/Group.cs
Tests/Models/Inheritance/GroupResource.cs
Tests/Tests.csproj

Hi Jouke, 
Looks like i missed one scenario related to relationship. without this change if we have a `Group` object that has `List<Shape> Shapes`, then it would return such response
```
{
"data": [
{
"type": "group",
"id": "1",
"links": {
"self": "http://localhost/api/groups/1/"
},
"attributes": {
"name": "Group 1"
},
"relationships": {
"shapes": {
"links": {
"self": "http://localhost/api/groups/1/relationships/shapes/",
"related": "http://localhost/api/groups/1/shapes/"
},
"data": [
{
"type": "shape",
"id": "1"
},
{
"type": "shape",
"id": "2"
},
{
"type": "shape",
"id": "3"
}
]
}
}
}
],
"links": {
"self": "http://localhost/api/groups"
},
"included": [
{
"type": "shape",
"id": "1",
"links": {
"self": "http://localhost/api/shape/1/"
},
"attributes": {
"color": "Purple"
}
},
{
"type": …
```

Updated IApiResourceProvider to care about relationship\include cases
